version: '3.9'


services:
  database:
    container_name: database
    image: postgres:15.2
    restart: always
    ports:
      - '5432:5436'
    links:
      - "api"
    env_file:
      - '.env'

  ui:
    container_name: ui
    build: ./ui
    restart: always
    ports:
      - "80:80"

  api:
    container_name: api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - '.env'
